# Generated by Django 3.0.4 on 2020-03-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200323_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_tect',
            new_name='choice_text',
        ),
    ]
